{{- $confFilesGlob := .Values.confFilesGlob -}}
# {{ $confFilesGlob }}
{{ if and (.Files.Glob $confFilesGlob) (not .Values.existingConfiguration) }}
apiVersion: v1
kind: ConfigMap
# {{ .Values.confFilesGlob }}
metadata:
  name: {{ include "cassandra.fullname" . }}-configuration
  labels: {{- include "cassandra.labels" . | nindent 4 }}
data:
{{ (.Files.Glob $confFilesGlob).AsConfig | indent 2 }}
{{ end }}
